<?php

function farm_quickweight_weight_all($asset){
  $logs = farm_quantity_log_asset($asset, 'weight',NULL, REQUEST_TIME, TRUE, 'farm_observation', $single=FALSE);

  if (!empty($logs)){

    $log_weights = array();
    foreach ($logs as $log){
      $data = farm_quantity_log_data($log, 'weight');
      foreach ($data as $quantity){
        $quantity['timestamp'] = $log->timestamp;
        $log_weights[] = $quantity;
      }
    }
    return $log_weights;
  }
  return array();
}

function farm_quickweight_weight_dlwg($asset){
  $logs = farm_quickweight_weight_all($asset);
  $dailyliveweightgain = array();



  if (count($logs)>1){
    if (($logs[0]['units']) == ($logs[1]['units'])){

    $most_recent = $logs[0]['timestamp'];
    $prevous_record = $logs[1]['timestamp'];

    $weight_difference = $logs[0]['value']-$logs[1]['value'];

    $timediff = $most_recent- $prevous_record;
    $timediff_days = round($timediff/86400,2);

    $dlwg = round($weight_difference/$timediff_days,3);

    $dailyliveweightgain = array("most_recent" => $most_recent, "previous_record" => $prevous_record, "value" => $dlwg, "units" => $logs[0]['units']);
  }
  }
  return $dailyliveweightgain;
}




function farm_quickweight_entity_view_alter(&$build,$type){
    if ($type != 'farm_asset' || empty($build['#entity'])) {

    return;
  }

  // Alias the asset variable.
  $asset = $build['#entity'];
  $asset_uri = entity_uri('farm_asset', $asset);

  // If it isn't an animal asset, bail.
  if ($asset->type != 'animal') {
    return;
  }
  // Get the daily liveweight gains for the animal - if there is none - it will not put the title in.
  $dlwg = farm_quickweight_weight_dlwg($asset);
  if (!empty($dlwg)){

    $output = t('<p><strong>Daily Liveweight Gain: </strong>') . $dlwg['value'] . ' ' .$dlwg['units'] . t('/day between @date1 and @date2', array('@date1' => date('d/m/Y',$dlwg['previous_record']), '@date2' => date('d/m/Y',$dlwg['most_recent'])));
  }
  // If the animal has an inventory greater than 1, add "(average)".
  $inventory = farm_inventory($asset);
  if ($inventory > 1) {
    $output .= ' (' . t('average') . ')';
  }

  // Add it to the build array.
  $build['dlwg'] = array(
    '#markup' => $output,
    '#prefix' => '<div class="dlwg">',
    '#suffix' => '</div>',
    '#weight' => -119,
  );
}
